### ISSUE TITLE
Bug in line 67 of pycvss3.py

### ISSUE THREAD

**Issue by hamkovic** [toolswatch/pycvss3#2]
Hi, there is a bug where I cannot calculate the following vector:

CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L/E:H/RL:O/RC:C

Seems like the code breaks when the Scope is set to Changed.

On line 67 of pycvss3.py:
self.splitted_2 = self.vectors[2:3][0].split(':')

Should be changed to:
self.splitted_2 = self.vectors[3:4][0].split(':')

**Comment by toolswatch** [comment]
fixed
